title: simple-wiki-theme
description: simple-wiki-theme is a jekyll theme originally based on git-wiki
show_downloads: true
git_branch: master
logo_url: https://raw.githubusercontent.com/claytonboss7/githubpages/gh-pages/_site/assets/images/logo.png
google_analytics:
wiki_folder: wiki
custom_head: false
custom_sidebar: false
custom_footer: false
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag