title: simple-wiki-theme
description: simple-wiki-theme is a jekyll theme originally based on git-wiki
show_downloads: true
git_branch: master
logo_url: https://www.crew-united.com/Media/Images/1000/1000632/1000632.big.jpg
google_analytics:
wiki_folder: wiki
custom_head: true
custom_sidebar: false
custom_footer: false
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag