title: voyajer-sf-wiki
description: documentation for the voyajer app and its implementation in Salesforce.com \:shipit\:
show_downloads: true
git_branch: gh-pages
logo_url: https://www.crew-united.com/Media/Images/1000/1000632/1000632.big.jpg
logo_url2: https://upload.wikimedia.org/wikipedia/commons/4/4e/Wiki-black.png
google_analytics:
wiki_folder: wiki
custom_head: false
custom_sidebar: false
custom_footer: false
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag