title: simple-wiki-theme
description: simple-wiki-theme is a jekyll theme originally based on git-wiki
show_downloads: true
git_branch: gh-pages
logo_url: https://github.com/claytonboss7/githubpages/blob/gh-pages/assets/images/logo8.png
google_analytics:
wiki_folder: wiki
custom_head: true
custom_sidebar: false
custom_footer: false
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag