title: voyajer-wiki
description: documentation for the voyajer app
show_downloads: true
git_branch: gh-pages
logo_url: https://raw.githubusercontent.com/claytonboss7/githubpages/7a6aabcb2cfff5c0c5045a2d6fc422d9f1d4767a/_site/assets/images/logonew.jpg
google_analytics:
wiki_folder: wiki
custom_head: false
custom_sidebar: false
custom_footer: false
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag